/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PracticaWordle.InterfazGrafica.ventanas;

/**
 *
 * @author Usuario
 */
public class Estadisticas extends javax.swing.JPanel {

    /**
     * Creates new form Opciones
     */
    public Estadisticas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombreUsuario = new javax.swing.JLabel();
        jTextFieldCampoNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDatos = new javax.swing.JTextArea();
        jButtonMostrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombreUsuario.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabelNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombreUsuario.setText("Introduce tu nombre de usuario: ");
        add(jLabelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jTextFieldCampoNombre.setBackground(new java.awt.Color(204, 204, 204));
        add(jTextFieldCampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 52, 340, 30));

        jTextAreaDatos.setBackground(new java.awt.Color(204, 204, 204));
        jTextAreaDatos.setColumns(20);
        jTextAreaDatos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDatos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 630, 220));

        jButtonMostrar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonMostrar.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jButtonMostrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMostrar.setText("MOSTRAR");
        add(jButtonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 190, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PracticaWordle/InterfazGrafica/imagenes/wallpaper_hd.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 360));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDatos;
    private javax.swing.JTextField jTextFieldCampoNombre;
    // End of variables declaration//GEN-END:variables
}
