/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PracticaWordle.InterfazGrafica.ventanas;

/**
 *
 * @author Usuario
 */
public class Jugar extends javax.swing.JPanel {

    /**
     * Creates new form Jugar
     */
    public Jugar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToggleButtonJugar = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(770, 360));
        setPreferredSize(new java.awt.Dimension(770, 360));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 680, 270));

        jToggleButtonJugar.setBackground(new java.awt.Color(204, 204, 204));
        jToggleButtonJugar.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jToggleButtonJugar.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonJugar.setText("JUGAR");
        add(jToggleButtonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 20, 310, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PracticaWordle/InterfazGrafica/imagenes/wallpaper_hd.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 360));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButtonJugar;
    // End of variables declaration//GEN-END:variables
}
